kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: fluxcd-notifications-otel-adapter
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
