apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../fluxcd-notifications-otel-adapter

patches:
  - target:
      kind: Service
      name: fluxcd-notifications-otel-adapter
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: fluxcd-notifications-otel-adapter
      spec:
        type: NodePort
